[project]
name = "mental-health-therapist"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain-community>=0.4.1",
    "langchain-groq>=1.0.1",
    "streamlit>=1.51.0",
]
